development:
  host: localhost
  database: licence_finder_development
  persist_in_safe_mode: true

test:
  host: localhost
  database: licence_finder_test
  autocreate_indexes: true

# set these environment variables on your prod server
production:
  uri: <%= ENV['GOVUK_MONGO_URI'] %>
